Upgrade third-party versions
extreal-dev/Extreal.Learning.Multiplay.NGO pull request #8
Opened 2024-02-06 06:28 UTC by sus-yoshikane-t

# 何の変更を加えましたか？

- Unityのバージョンを上げました
- Extrealの各モジュールのバージョンを上げました
- 依存ライブラリのバージョンを上げました

# 何を確認しましたか?

- [x] GuideのLearningページの通りに学習を進められることを確認しました

# レビュアーへのメッセージ

2024-02-14 02:01 UTC, sus-taguchi-t requested changes

2024-02-14 02:01 UTC, sus-taguchi-t commented on Packages/manifest.json
>      "com.unity.ide.visualstudio": "2.0.22",
バージョンの修正をお願いします。

2024-02-14 02:01 UTC, sus-taguchi-t commented on Packages/manifest.json
> +    "jp.co.tis.extreal.integration.multiplay.ngo": "https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO.git#1.3.0-next.1",
バージョンの修正をお願いします。
https://github.com/orgs/extreal-dev/projects/1?pane=issue&itemId=45885839

2024-02-14 04:34 UTC, sus-yoshikane-t commented on Packages/manifest.json
> +    "jp.co.tis.extreal.integration.multiplay.ngo": "https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO.git#1.3.0-next.1",
修正しました。
https://github.com/extreal-dev/Extreal.Learning.Multiplay.NGO/pull/8/commits/7e501171a2fe1f069699f7c7a1ee47a8e3ffc253

2024-02-14 04:35 UTC, sus-yoshikane-t commented on Packages/manifest.json
>      "com.unity.ide.visualstudio": "2.0.22",
修正しました。
https://github.com/extreal-dev/Extreal.Learning.Multiplay.NGO/pull/8/commits/7e501171a2fe1f069699f7c7a1ee47a8e3ffc253

2024-02-19 02:08 UTC, sus-taguchi-t commented on Packages/manifest.json
>      "com.unity.ide.visualstudio": "2.0.22",
確認しました。

2024-02-19 02:09 UTC, sus-taguchi-t commented on Packages/manifest.json
> +    "jp.co.tis.extreal.integration.multiplay.ngo": "https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO.git#1.3.0-next.1",
確認しました。

2024-02-19 02:22 UTC, sus-taguchi-t approved these changes

2024-02-19 02:22 UTC, merged